/* eslint-disable */
/* tslint:disable */
/* auto-generated by NAPI-RS */

export interface ScanOptions {
  root: string;
  extensions: string[];
  ignorePatterns: string[];
  includeTests: boolean;
}

export interface ScanResultItem {
  filePath: string;
  lineStart: number;
  lineEnd: number;
  codeSnippet: string;
  kind: string;
  name: string;
  reason: string;
  confidence: number;
}

export interface ScanResult {
  items: ScanResultItem[];
  totalFilesScanned: number;
  scanDurationMs: number;
}

/**
 * Entry point for Node.js via NAPI
 * Runs the CLI with the given arguments
 */
export function run(args: string[]): Promise<number>;

/**
 * Programmatic scan API for Node.js consumers
 */
export function scan(options: ScanOptions): Promise<ScanResult>;
