/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Entry point for Node.js via NAPI
 * Runs the CLI with the given arguments
 */
export declare function run(args: Array<string>): Promise<number>
/** Scan a directory for dead code (NAPI export for programmatic use) */
export interface ScanOptions {
  root: string
  extensions: Array<string>
  ignorePatterns: Array<string>
  includeTests: boolean
}
export interface ScanResultItem {
  filePath: string
  lineStart: number
  lineEnd: number
  codeSnippet: string
  kind: string
  name: string
  reason: string
  confidence: number
}
export interface ScanResult {
  items: Array<ScanResultItem>
  totalFilesScanned: number
  scanDurationMs: number
}
/** Programmatic scan API for Node.js consumers */
export declare function scan(options: ScanOptions): Promise<ScanResult>
